spring:
  profiles:
    active:
    - dev

---
  server:
    port: 8201
  spring:
    profiles: dev
    application:
      name: microconfig-config-client
  eureka:
    client: 
      service-url:
        defaultZone: http://edmin:housh@eureka-dev.com:7001/eureka
      
---
  server:
    port: 8102
  spring:
    profiles: beta
    application:
      name: microconfig-config-client
  eureka:
    client: 
      service-url:
        defaultZone: http://edmin:housh@eureka-beta.com:7001/eureka
